In [1]:
import pandas as pd
import numpy as np
print("pandas version is",pd.__version__)

pandas version is 3.0.6

In [26]:
df=pd.read_csv("C:\\Users\\ABC\\Downloads\\Student_Performance.csv")
df.head()
print("Shape:",df.shape)
print("Columns")
print(df.columns.tolist())
print("\nData types:")
print(df.dtypes)
print("\nFirst 5 rows:")
display(df.head())
print("\nlast 5 rows:")
display(df.tail())
print("\ndataset information")
print(df.info())

Shape: (61, 13)
Columns
['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Attendance', 'Study_Hours', 'Assignment_Score', 'Exam_Score', 'City', 'Enrollment_Date', 'Fee_Status', 'Placement_Status']

Data types:
Student_ID            int64
Name                    str
Age                   int64
Gender                  str
Department              str
Attendance          float64
Study_Hours         float64
Assignment_Score      int64
Exam_Score            int64
City                    str
Enrollment_Date         str
Fee_Status              str
Placement_Status        str
dtype: object

First 5 rows:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed

last 5 rows:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

dataset information
<class 'pandas.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        61 non-null     int64
 1   Name              61 non-null     str
 2   Age               61 non-null     int64
 3   Gender            61 non-null     str
 4   Department        60 non-null     str
 5   Attendance        59 non-null     float64
 6   Study_Hours       59 non-null     float64
 7   Assignment_Score  61 non-null     int64
 8   Exam_Score        61 non-null     int64
 9   City              61 non-null     str
 10  Enrollment_Date   61 non-null     str
 11  Fee_Status        61 non-null     str
 12  Placement_Status  61 non-null     str
dtypes: float64(2), int64(4), str(7)
memory usage: 6.3 KB
None

In [15]:
df.size

793

In [9]:
print("summary statistics:")
display(df.select_dtypes(include="number").describe())

summary statistics:

,Student_ID,Age,Attendance,Study_Hours,Assignment_Score,Exam_Score
count,61.000000,61.000000,59.000000,59.000000,61.000000,61.000000
mean,1030.196721,21.688525,86.084746,4.633898,72.688525,80.147541
std,17.479340,1.297960,8.569328,2.084475,15.941080,14.473926
min,1001.000000,20.000000,68.600000,1.500000,45.000000,53.000000
25%,1015.000000,21.000000,79.150000,2.950000,60.000000,70.000000
50%,1030.000000,22.000000,85.100000,4.300000,72.000000,80.000000
75%,1045.000000,23.000000,94.450000,6.300000,84.000000,95.000000
max,1060.000000,24.000000,98.900000,8.400000,98.000000,99.000000

In [10]:
print("\nunique departments:")
print(df["Department"].unique())

unique departments:
<StringArray>
['Data Science', 'Cloud', 'Python', 'AI', ' ai ', 'data science', 'python ',
 nan]
Length: 8, dtype: str

In [17]:
print("\n Department counts")
print(df["Department"].value_counts(dropna=False))

 Department counts
Department
AI              25
Data Science    16
Cloud           10
Python           6
 ai              1
data science     1
python           1
NaN              1
Name: count, dtype: int64

In [27]:
print("one column")
display(df["Exam_Score"])

one column

0     78
1     99
2     70
3     64
4     76
      ..
56    64
57    56
58    99
59    99
60    73
Name: Exam_Score, Length: 61, dtype: int64

In [21]:
print("Multiple columns")
display(df[["Name","Department","Exam_Score"]])

Multiple columns

       Name    Department  Exam_Score
0      Ravi  Data Science          78
1     Priya         Cloud          99
2      Arun        Python          70
3     Meena  Data Science          64
4     Kiran            AI          76
..      ...           ...         ...
56   Venkat            AI          64
57  Sahithi            AI          56
58    Akash            AI          99
59  Madhavi            AI          99
60    Manoj         Cloud          73

[61 rows x 3 columns]

In [22]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Attendance',
       'Study_Hours', 'Assignment_Score', 'Exam_Score', 'City',
       'Enrollment_Date', 'Fee_Status', 'Placement_Status'],
      dtype='str')

In [23]:
print("First row:")
display(df.loc[0])

First row:

Student_ID                   1001
Name                         Ravi
Age                            21
Gender                     Female
Department           Data Science
Attendance                   84.0
Study_Hours                   5.5
Assignment_Score               63
Exam_Score                     78
City                Visakhapatnam
Enrollment_Date        2026-01-05
Fee_Status                   Paid
Placement_Status           Placed
Name: 0, dtype: object

In [24]:
print("specific values:")
print(df.loc[0,"Exam_Score"])

specific values:
78

In [28]:
print("First row")
display(df.iloc[0])

print("First 5 rows,first 4 columns:")
display(df.iloc[0:5,0:4])

First row

Student_ID                   1001
Name                         Ravi
Age                            21
Gender                     Female
Department           Data Science
Attendance                   84.0
Study_Hours                   5.5
Assignment_Score               63
Exam_Score                     78
City                Visakhapatnam
Enrollment_Date        2026-01-05
Fee_Status                   Paid
Placement_Status           Placed
Name: 0, dtype: object

First 5 rows,first 4 columns:

   Student_ID   Name  Age  Gender
0        1001   Ravi   21  Female
1        1002  Priya   23    Male
2        1003   Arun   23  Female
3        1004  Meena   21    Male
4        1005  Kiran   22    Male

In [29]:
print("Students with exam score > 80:")
display(df[df["Exam_Score"] > 80])

print("Students with attendance >=85 ")
display(df[df["Attendance"]>=85])

Students with exam score > 80:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
7,1008,Rahul,20,Male,ai,76.6,4.1,97,91,Vijayawada,2026-01-26,Pending,Placed
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed
10,1011,Sneha,20,Female,AI,94.5,8.0,56,94,Visakhapatnam,2026-02-04,Paid,Placed
13,1014,Naveen,23,Male,data science,94.4,6.2,45,82,Bengaluru,2026-02-13,Paid,Placed
14,1015,Pooja,24,Male,AI,97.0,4.0,91,96,Visakhapatnam,2026-02-16,Paid,Placed
16,1017,Swathi,20,Male,AI,88.7,3.6,76,91,Visakhapatnam,2026-02-22,Paid,Placed
18,1019,Keerthi,21,Male,Data Science,79.5,7.4,92,99,Chennai,2026-02-28,Paid,Not Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
21,1022,Varun,21,Male,AI,76.8,5.4,89,88,Visakhapatnam,2026-03-09,Pending,Placed
22,1023,Asha,23,Female,AI,77.5,3.6,97,84,Chennai,2026-03-12,Paid,Placed
25,1026,Sanjana,20,Male,Python,98.8,5.8,83,98,Vijayawada,2026-03-21,Pending,Placed
28,1029,Tarun,21,Male,Data Science,83.3,5.9,73,95,Hyderabad,2026-03-30,Paid,Not Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
33,1034,Mounika,22,Male,Cloud,77.5,7.7,95,99,Bengaluru,2026-04-14,Pending,Not Placed
35,1036,Harini,22,Female,python,83.8,5.6,66,88,Chennai,2026-04-20,Paid,Placed
37,1038,Shreya,23,Female,AI,75.8,6.2,58,84,Bengaluru,2026-04-26,Paid,Not Placed
38,1039,Karthik,22,Male,Python,86.3,3.8,72,84,Hyderabad,2026-04-29,Paid,Not Placed
40,1041,Rakesh,22,Male,AI,83.1,8.4,91,99,Hyderabad,2026-05-05,Paid,Placed
41,1042,Pallavi,21,Male,Data Science,96.1,7.4,93,99,Hyderabad,2026-05-08,Paid,Placed
42,1043,Karthik,22,Female,AI,81.5,7.5,74,97,Chennai,2026-05-11,Paid,Not Placed
43,1044,Sowmya,22,Female,Cloud,78.9,NaN,90,88,Hyderabad,2026-05-14,Paid,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
48,1049,Abhishek,21,Male,Data Science,83.5,7.3,70,99,Chennai,2026-05-29,Paid,Placed
50,1051,Lokesh,22,Female,Cloud,91.8,8.3,92,99,Visakhapatnam,2026-06-04,Paid,Not Placed
52,1053,Chandu,20,Male,Cloud,98.8,7.4,83,99,Chennai,2026-06-10,Paid,Not Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed

Students with attendance >=85

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed
8,1009,Divya,20,Female,Data Science,89.7,4.3,67,77,Vijayawada,2026-01-29,Paid,Not Placed
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed
10,1011,Sneha,20,Female,AI,94.5,8.0,56,94,Visakhapatnam,2026-02-04,Paid,Placed
12,1013,Kavya,21,Male,Python,95.5,3.0,45,59,Hyderabad,2026-02-10,Paid,Not Placed
13,1014,Naveen,23,Male,data science,94.4,6.2,45,82,Bengaluru,2026-02-13,Paid,Placed
14,1015,Pooja,24,Male,AI,97.0,4.0,91,96,Visakhapatnam,2026-02-16,Paid,Placed
15,1016,Harish,20,Male,AI,92.3,3.3,78,66,Bengaluru,2026-02-19,Paid,Not Placed
16,1017,Swathi,20,Male,AI,88.7,3.6,76,91,Visakhapatnam,2026-02-22,Paid,Placed
19,1020,Rohit,24,Male,AI,97.1,2.5,69,70,Visakhapatnam,2026-03-03,Paid,Not Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
25,1026,Sanjana,20,Male,Python,98.8,5.8,83,98,Vijayawada,2026-03-21,Pending,Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
32,1033,Pranav,23,Male,AI,90.3,1.9,60,53,Bengaluru,2026-04-11,Paid,Not Placed
36,1037,Ganesh,23,Male,AI,87.7,4.6,73,80,Vijayawada,2026-04-23,Paid,Placed
38,1039,Karthik,22,Male,Python,86.3,3.8,72,84,Hyderabad,2026-04-29,Paid,Not Placed
39,1040,Lavanya,23,Female,Data Science,98.3,2.6,49,54,Hyderabad,2026-05-02,Paid,Not Placed
41,1042,Pallavi,21,Male,Data Science,96.1,7.4,93,99,Hyderabad,2026-05-08,Paid,Placed
44,1045,Surya,23,Female,AI,88.0,1.8,96,80,Bengaluru,2026-05-17,Pending,Not Placed
45,1046,Ishita,23,Male,Python,88.7,3.6,49,69,Visakhapatnam,2026-05-20,Paid,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
49,1050,Sravani,20,Female,AI,85.7,3.4,70,70,Hyderabad,2026-06-01,Pending,Not Placed
50,1051,Lokesh,22,Female,Cloud,91.8,8.3,92,99,Visakhapatnam,2026-06-04,Paid,Not Placed
52,1053,Chandu,20,Male,Cloud,98.8,7.4,83,99,Chennai,2026-06-10,Paid,Not Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed

In [30]:
result=df[
       (df["Exam_Score"] > 80) & (df["Attendance"]>=80)]
display(result)

print("ai or data science students:")
display(df[df["Department"].isin(["AI","Data Science"])])

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
9,1010,Rahul,22,Female,Python,94.2,7.4,53,84,Bengaluru,2026-02-01,Paid,Not Placed
10,1011,Sneha,20,Female,AI,94.5,8.0,56,94,Visakhapatnam,2026-02-04,Paid,Placed
13,1014,Naveen,23,Male,data science,94.4,6.2,45,82,Bengaluru,2026-02-13,Paid,Placed
14,1015,Pooja,24,Male,AI,97.0,4.0,91,96,Visakhapatnam,2026-02-16,Paid,Placed
16,1017,Swathi,20,Male,AI,88.7,3.6,76,91,Visakhapatnam,2026-02-22,Paid,Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
25,1026,Sanjana,20,Male,Python,98.8,5.8,83,98,Vijayawada,2026-03-21,Pending,Placed
28,1029,Tarun,21,Male,Data Science,83.3,5.9,73,95,Hyderabad,2026-03-30,Paid,Not Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
35,1036,Harini,22,Female,python,83.8,5.6,66,88,Chennai,2026-04-20,Paid,Placed
38,1039,Karthik,22,Male,Python,86.3,3.8,72,84,Hyderabad,2026-04-29,Paid,Not Placed
40,1041,Rakesh,22,Male,AI,83.1,8.4,91,99,Hyderabad,2026-05-05,Paid,Placed
41,1042,Pallavi,21,Male,Data Science,96.1,7.4,93,99,Hyderabad,2026-05-08,Paid,Placed
42,1043,Karthik,22,Female,AI,81.5,7.5,74,97,Chennai,2026-05-11,Paid,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
48,1049,Abhishek,21,Male,Data Science,83.5,7.3,70,99,Chennai,2026-05-29,Paid,Placed
50,1051,Lokesh,22,Female,Cloud,91.8,8.3,92,99,Visakhapatnam,2026-06-04,Paid,Not Placed
52,1053,Chandu,20,Male,Cloud,98.8,7.4,83,99,Chennai,2026-06-10,Paid,Not Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed

ai or data science students:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed
8,1009,Divya,20,Female,Data Science,89.7,4.3,67,77,Vijayawada,2026-01-29,Paid,Not Placed
10,1011,Sneha,20,Female,AI,94.5,8.0,56,94,Visakhapatnam,2026-02-04,Paid,Placed
14,1015,Pooja,24,Male,AI,97.0,4.0,91,96,Visakhapatnam,2026-02-16,Paid,Placed
15,1016,Harish,20,Male,AI,92.3,3.3,78,66,Bengaluru,2026-02-19,Paid,Not Placed
16,1017,Swathi,20,Male,AI,88.7,3.6,76,91,Visakhapatnam,2026-02-22,Paid,Placed
17,1018,Ajay,22,Male,Data Science,NaN,3.8,98,73,Visakhapatnam,2026-02-25,Pending,Placed
18,1019,Keerthi,21,Male,Data Science,79.5,7.4,92,99,Chennai,2026-02-28,Paid,Not Placed
19,1020,Rohit,24,Male,AI,97.1,2.5,69,70,Visakhapatnam,2026-03-03,Paid,Not Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
21,1022,Varun,21,Male,AI,76.8,5.4,89,88,Visakhapatnam,2026-03-09,Pending,Placed
22,1023,Asha,23,Female,AI,77.5,3.6,97,84,Chennai,2026-03-12,Paid,Placed
23,1024,Dinesh,22,Female,Data Science,83.1,4.4,45,63,Chennai,2026-03-15,Paid,Not Placed
24,1025,Teja,22,Female,Data Science,81.9,3.3,60,63,Bengaluru,2026-03-18,Paid,Not Placed
26,1027,sneha,24,Male,AI,73.5,2.1,49,57,Vijayawada,2026-03-24,Pending,Not Placed
27,1028,Bhavya,23,Male,Data Science,68.6,1.5,66,54,Visakhapatnam,2026-03-27,Paid,Not Placed
28,1029,Tarun,21,Male,Data Science,83.3,5.9,73,95,Hyderabad,2026-03-30,Paid,Not Placed
29,1030,Nisha,22,Female,AI,73.5,NaN,47,61,Visakhapatnam,2026-04-02,Paid,Not Placed
30,1031,Sai,20,Male,Data Science,79.4,2.0,56,63,Bengaluru,2026-04-05,Paid,Not Placed
31,1032,Deepika,20,Male,AI,91.1,4.3,70,82,Bengaluru,2026-04-08,Paid,Placed
32,1033,Pranav,23,Male,AI,90.3,1.9,60,53,Bengaluru,2026-04-11,Paid,Not Placed
36,1037,Ganesh,23,Male,AI,87.7,4.6,73,80,Vijayawada,2026-04-23,Paid,Placed
37,1038,Shreya,23,Female,AI,75.8,6.2,58,84,Bengaluru,2026-04-26,Paid,Not Placed
39,1040,Lavanya,23,Female,Data Science,98.3,2.6,49,54,Hyderabad,2026-05-02,Paid,Not Placed
40,1041,Rakesh,22,Male,AI,83.1,8.4,91,99,Hyderabad,2026-05-05,Paid,Placed
41,1042,Pallavi,21,Male,Data Science,96.1,7.4,93,99,Hyderabad,2026-05-08,Paid,Placed
42,1043,Karthik,22,Female,AI,81.5,7.5,74,97,Chennai,2026-05-11,Paid,Not Placed
44,1045,Surya,23,Female,AI,88.0,1.8,96,80,Bengaluru,2026-05-17,Pending,Not Placed
46,1047,Manoj,20,Female,AI,94.8,5.3,56,86,Hyderabad,2026-05-23,Paid,Placed
47,1048,Neha,20,Male,Data Science,75.1,3.8,60,70,Chennai,2026-05-26,Pending,Placed
48,1049,Abhishek,21,Male,Data Science,83.5,7.3,70,99,Chennai,2026-05-29,Paid,Placed
49,1050,Sravani,20,Female,AI,85.7,3.4,70,70,Hyderabad,2026-06-01,Pending,Not Placed
54,1055,Yashwanth,21,Female,Data Science,76.7,4.4,77,75,Bengaluru,2026-06-16,Paid,Not Placed
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed

In [33]:
print("Highest exam scores:")
display(df.sort_values("Exam_Score", ascending=False).head(10))

print("Lowest attendance:")
display(df.sort_values("Attendance", ascending=True).head(10))

Highest exam scores:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
18,1019,Keerthi,21,Male,Data Science,79.5,7.4,92,99,Chennai,2026-02-28,Paid,Not Placed
20,1021,Lakshmi,23,Female,Data Science,98.2,6.5,84,99,Bengaluru,2026-03-06,Paid,Placed
40,1041,Rakesh,22,Male,AI,83.1,8.4,91,99,Hyderabad,2026-05-05,Paid,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
48,1049,Abhishek,21,Male,Data Science,83.5,7.3,70,99,Chennai,2026-05-29,Paid,Placed
50,1051,Lokesh,22,Female,Cloud,91.8,8.3,92,99,Visakhapatnam,2026-06-04,Paid,Not Placed
52,1053,Chandu,20,Male,Cloud,98.8,7.4,83,99,Chennai,2026-06-10,Paid,Not Placed
55,1056,Bhargavi,21,Female,Cloud,95.4,6.4,74,99,Chennai,2026-06-19,Pending,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed

Lowest attendance:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
27,1028,Bhavya,23,Male,Data Science,68.6,1.5,66,54,Visakhapatnam,2026-03-27,Paid,Not Placed
51,1052,Anusha,23,Male,NaN,69.4,4.7,65,77,Hyderabad,2026-06-07,Pending,Not Placed
29,1030,Nisha,22,Female,AI,73.5,NaN,47,61,Visakhapatnam,2026-04-02,Paid,Not Placed
26,1027,sneha,24,Male,AI,73.5,2.1,49,57,Vijayawada,2026-03-24,Pending,Not Placed
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed
47,1048,Neha,20,Male,Data Science,75.1,3.8,60,70,Chennai,2026-05-26,Pending,Placed
37,1038,Shreya,23,Female,AI,75.8,6.2,58,84,Bengaluru,2026-04-26,Paid,Not Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
7,1008,Rahul,20,Male,ai,76.6,4.1,97,91,Vijayawada,2026-01-26,Pending,Placed
54,1055,Yashwanth,21,Female,Data Science,76.7,4.4,77,75,Bengaluru,2026-06-16,Paid,Not Placed

In [39]:
work=df.copy()
work["Passed"]=work["Exam_Score"]>=50
work["Total_Score"]=work["Assignment_Score"]+work["Exam_Score"]
work["Average_Score"]=work[["Assignment_Score","Exam_Score"]].mean(axis=1)

display(work[["Name","Assignment_Score","Exam_Score","Total_Score","Average_Score","Passed"]])

       Name  Assignment_Score  Exam_Score  Total_Score  Average_Score  Passed
0      Ravi                63          78          141           70.5    True
1     Priya                61          99          160           80.0    True
2      Arun                63          70          133           66.5    True
3     Meena                72          64          136           68.0    True
4     Kiran                70          76          146           73.0    True
..      ...               ...         ...          ...            ...     ...
56   Venkat                81          64          145           72.5    True
57  Sahithi                67          56          123           61.5    True
58    Akash                54          99          153           76.5    True
59  Madhavi                98          99          197           98.5    True
60    Manoj                97          73          170           85.0    True

[61 rows x 6 columns]

In [43]:
work["Performance_Level"]=np.where(
    work["Exam_Score"]>=85,"Excellent",
    np.where(work["Exam_Score"]>=70,"Good","Needs Improvement"))
display(work[["Name","Exam_Score","Performance_Level"]].head(10))

        Name  Exam_Score  Performance_Level
0       Ravi          78               Good
1      Priya          99          Excellent
2       Arun          70               Good
3      Meena          64  Needs Improvement
4      Kiran          76               Good
5     Suresh          77               Good
6     Anjali          74               Good
7      Rahul          91          Excellent
8      Divya          77               Good
9    Rahul            84               Good

In [45]:
renamed=df.rename(columns={"Exam_Score":" Final Exam Score",
                          "Study_Hours":"Daily Study Hours"
                           })
display(renamed.head())

,Student_ID,Name,Age,Gender,Department,Attendance,Daily Study Hours,Assignment_Score,Final Exam Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed

In [47]:
example=work.drop(columns=["Total_Score"])
display(example.head())
example=work.drop(index=[0,1])
display(example.head())

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status,Passed,Average_Score,Performance_level,Performance_Level
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed,True,70.5,Good,Good
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed,True,80.0,Excellent,Excellent
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed,True,66.5,Good,Good
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed,True,68.0,Needs Improvement,Needs Improvement
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed,True,73.0,Good,Good

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status,Passed,Total_Score,Average_Score,Performance_level,Performance_Level
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed,True,133,66.5,Good,Good
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed,True,136,68.0,Needs Improvement,Needs Improvement
4,1005,Kiran,22,Male,AI,NaN,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed,True,146,73.0,Good,Good
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed,True,158,79.0,Good,Good
6,1007,Anjali,24,Female,AI,73.8,4.9,70,74,Hyderabad,2026-01-23,Paid,Placed,True,144,72.0,Good,Good

In [48]:
print("Missing values by column")
print(df.isna().sum())

print("\nTotal missing values:")
print(df.isna().sum().sum())

Missing values by column
Student_ID          0
Name                0
Age                 0
Gender              0
Department          1
Attendance          2
Study_Hours         2
Assignment_Score    0
Exam_Score          0
City                0
Enrollment_Date     0
Fee_Status          0
Placement_Status    0
dtype: int64

Total missing values:
5

In [49]:
complete_rows=df.dropna()
print("Original shape:",df.shape)
print("After dropna:",complete_rows.shape)
display(complete_rows.head())

Original shape: (61, 13)
After dropna: (56, 13)

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
5,1006,Suresh,20,Female,AI,95.4,3.4,81,77,Chennai,2026-01-20,Paid,Not Placed

In [51]:
filled=df.copy()
filled["Attendance"]=filled["Attendance"].fillna(
    filled["Attendance"].median()
)

filled["Study_Hours"]=filled["Study_Hours"].fillna(
    filled["Study_Hours"].median()
)
filled["Department"]=filled["Department"].fillna("Unknown")
print("Remaining missing values")
print(filled.isna().sum())

display(filled)

Remaining missing values
Student_ID          0
Name                0
Age                 0
Gender              0
Department          0
Attendance          0
Study_Hours         0
Assignment_Score    0
Exam_Score          0
City                0
Enrollment_Date     0
Fee_Status          0
Placement_Status    0
dtype: int64

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
0,1001,Ravi,21,Female,Data Science,84.0,5.5,63,78,Visakhapatnam,2026-01-05,Paid,Placed
1,1002,Priya,23,Male,Cloud,76.1,8.4,61,99,Chennai,2026-01-08,Paid,Placed
2,1003,Arun,23,Female,Python,98.9,2.0,63,70,Hyderabad,2026-01-11,Paid,Placed
3,1004,Meena,21,Male,Data Science,97.9,3.6,72,64,Visakhapatnam,2026-01-14,Paid,Not Placed
4,1005,Kiran,22,Male,AI,85.1,2.8,70,76,Vijayawada,2026-01-17,Paid,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Venkat,22,Male,AI,91.2,2.5,81,64,Hyderabad,2026-06-22,Paid,Not Placed
57,1058,Sahithi,23,Male,AI,97.5,2.4,67,56,Bengaluru,2026-06-25,Paid,Not Placed
58,1059,Akash,21,Male,AI,78.3,8.3,54,99,Hyderabad,2026-06-28,Pending,Placed
59,1060,Madhavi,20,Male,AI,85.1,6.5,98,99,Hyderabad,2026-07-01,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

In [57]:
time_df=pd.DataFrame({
    "Day":[1,2,3,4,5],
    "Temperature":[np.nan,20,32,np.nan,35]

})
display(time_df)
print("Forward Filling:")
display(time_df.ffill())

print("Backward Filling:")
display(time_df.bfill())

   Day  Temperature
0    1          NaN
1    2         20.0
2    3         32.0
3    4          NaN
4    5         35.0

Forward Filling:

   Day  Temperature
0    1          NaN
1    2         20.0
2    3         32.0
3    4         32.0
4    5         35.0

Backward Filling:

   Day  Temperature
0    1         20.0
1    2         20.0
2    3         32.0
3    4         35.0
4    5         35.0

In [60]:
print("Duplicate rows:",df.duplicated().sum())
print("Duplicate rows:")
display(df[df.duplicated(keep=False)])
df_no_duplicates=df.drop_duplicates()
print("Shape after removimg duplicate rows:",df_no_duplicates.shape)

Duplicate rows: 1
Duplicate rows:

,Student_ID,Name,Age,Gender,Department,Attendance,Study_Hours,Assignment_Score,Exam_Score,City,Enrollment_Date,Fee_Status,Placement_Status
11,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed
60,1012,Manoj,21,Male,Cloud,80.5,2.0,97,73,Chennai,2026-02-07,Paid,Placed

Shape after removimg duplicate rows: (60, 13)

In [61]:
print(df.dtypes)

Student_ID            int64
Name                    str
Age                   int64
Gender                  str
Department              str
Attendance          float64
Study_Hours         float64
Assignment_Score      int64
Exam_Score            int64
City                    str
Enrollment_Date         str
Fee_Status              str
Placement_Status        str
dtype: object

In [63]:
demo=pd.DataFrame({
    "Marks":["80","92","invalid","75"] 
})

demo["Marks"]=pd.to_numeric(demo["Marks"],errors="coerce")
print(demo)
print(demo.dtypes)

   Marks
0   80.0
1   92.0
2    NaN
3   75.0
Marks    float64
dtype: object

In [ ]:
names=pd.Series([" Ravi","PRIYA","Arun kumar","Meena"])
print("Clean Spaces:")
print(names.str.strip())
print("\nLower Case:")
print(names.str.strip().str.lower())
print("\nUpper Case:")
print(names.str.strip().str.upper())
print("\n Title Case:")
print(names.str.title())

Clean Spaces:
0          Ravi
1         PRIYA
2    Arun kumar
3         Meena
dtype: str

Lower Case:
0          ravi
1         priya
2    arun kumar
3         meena
dtype: str

Upper Case:
0          RAVI
1         PRIYA
2    ARUN KUMAR
3         MEENA
dtype: str

 Title Case:
0          Ravi
1         Priya
2    Arun Kumar
3         Meena
dtype: str

 Contains case:
0     True
1    False
2     True
3     True
dtype: bool

In [73]:
clean=df.copy()
clean["Name"]=clean["Name"].str.strip().str.title()
clean["Department"]=clean["Department"].str.strip().str.title()

clean["Department"]=clean["Department"].replace({
    "Ai":"AI",
    "Data science":"Data Science",
    "Python":"Python",
    "cloud":"Cloud" 
})
display(clean[["Name","Department"]].head(15))

      Name    Department
0     Ravi  Data Science
1    Priya         Cloud
2     Arun        Python
3    Meena  Data Science
4    Kiran            AI
5   Suresh            AI
6   Anjali            AI
7    Rahul            AI
8    Divya  Data Science
9    Rahul        Python
10   Sneha            AI
11   Manoj         Cloud
12   Kavya        Python
13  Naveen  Data Science
14   Pooja            AI

In [78]:
ai_students=clean[
    clean["Department"].str.contains("AI",case=False,na=False)
    ]
display(ai_students[["Name","Department","Exam_Score"]])

       Name Department  Exam_Score
4     Kiran         AI          76
5    Suresh         AI          77
6    Anjali         AI          74
7     Rahul         AI          91
10    Sneha         AI          94
14    Pooja         AI          96
15   Harish         AI          66
16   Swathi         AI          91
19    Rohit         AI          70
21    Varun         AI          88
22     Asha         AI          84
26    Sneha         AI          57
29    Nisha         AI          61
31  Deepika         AI          82
32   Pranav         AI          53
36   Ganesh         AI          80
37   Shreya         AI          84
40   Rakesh         AI          99
42  Karthik         AI          97
44    Surya         AI          80
46    Manoj         AI          86
49  Sravani         AI          70
56   Venkat         AI          64
57  Sahithi         AI          56
58    Akash         AI          99
59  Madhavi         AI          99

In [81]:
date_df =clean.copy()
date_df["Enrollment_Date"]=pd.to_datetime(
    date_df["Enrollment_Date"]

)
date_df["Enrollment_Year"]=date_df["Enrollment_Date"].dt.year
date_df["Enrollment_Month"]=date_df["Enrollment_Date"].dt.month
date_df["Enrollment_Day"]=date_df["Enrollment_Date"].dt.day
display(date_df[["Enrollment_Date","Enrollment_Year","Enrollment_Month","Enrollment_Day"]].head(10))

  Enrollment_Date  Enrollment_Year  Enrollment_Month  Enrollment_Day
0      2026-01-05             2026                 1               5
1      2026-01-08             2026                 1               8
2      2026-01-11             2026                 1              11
3      2026-01-14             2026                 1              14
4      2026-01-17             2026                 1              17
5      2026-01-20             2026                 1              20
6      2026-01-23             2026                 1              23
7      2026-01-26             2026                 1              26
8      2026-01-29             2026                 1              29
9      2026-02-01             2026                 2               1

In [82]:
dept_avg=(
    clean.groupby("Department")["Exam_Score"].mean().sort_values(ascending=False))
display(dept_avg)

Department
Cloud           87.900000
AI              79.769231
Python          78.857143
Data Science    76.882353
Name: Exam_Score, dtype: float64

In [83]:
summary=(
    clean.groupby("Department")["Exam_Score"].agg(["count","mean","min","max"])
    .round(2)
)
display(summary)

              count   mean  min  max
Department
AI               26  79.77   53   99
Cloud            10  87.90   72   99
Data Science     17  76.88   54   99
Python            7  78.86   59   98

In [85]:
#merge
students=clean[["Student_ID","Department","Name"]].copy()
attendance=clean[["Student_ID","Attendance"]].copy()
merged=pd.merge(
    students,
    attendance,
    on="Student_ID",
    how="inner"
)
display(merged.head())

   Student_ID    Department   Name  Attendance
0        1001  Data Science   Ravi        84.0
1        1002         Cloud  Priya        76.1
2        1003        Python   Arun        98.9
3        1004  Data Science  Meena        97.9
4        1005            AI  Kiran         NaN