In [ ]:
import pandas as pd
import numpy as np
print("pandas version is",pd.__version__)

pandas version is 3.0.6

In [11]:
marks=pd.Series([80,90,75,88])
print(marks)
student_marks=pd.Series(
    [85,92,76],
    index=["Ravi","priya","arun"]
    )
print("Custom index:")
print(student_marks)

0    80
1    90
2    75
3    88
dtype: int64
Custom index:
Ravi     85
priya    92
arun     76
dtype: int64

In [8]:

sample=pd.DataFrame({
    "name":["Ravi","priya","arun"],
    "age":[21,20,22],
    "marks":[85,92,76]
})
sample

    name  age  marks
0   Ravi   21     85
1  priya   20     92
2   arun   22     76

In [7]:

data=[
  ["ravi",21,85],
  ["priya",20,92],
  ["Arun",22,76]
]
pd.DataFrame(data,columns=["name","age","marks"])

    name  age  marks
0   ravi   21     85
1  priya   20     92
2   Arun   22     76

In [ ]:
arr=np.array([[1,80],[2,90],[3,75]])
pd.DataFrame(arr,columns=["std_id","marks"])

   std_id  marks
0       1     80
1       2     90
2       3     75

In [ ]:
df=pd.read_csv("C:\\Users\\ABC\\Downloads\\Student_Performance.csv")
df.head()